"""v2_mediator_foundation

Revision ID: 35a5913fdbe6
Revises: dbace7809ca5
Create Date: 2026-03-18 14:17:02.976545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a5913fdbe6'
down_revision: Union[str, None] = 'dbace7809ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediator_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('penalty_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediator_penalties_id'), 'mediator_penalties', ['id'], unique=False)
    op.create_index(op.f('ix_mediator_penalties_mediator_id'), 'mediator_penalties', ['mediator_id'], unique=False)
    op.create_table('mediator_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aadhaar_number_hash', sa.String(length=255), nullable=True),
    sa.Column('aadhaar_doc_url', sa.String(length=500), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('mediator_type', sa.String(length=30), nullable=False),
    sa.Column('operating_zone', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('badge_issued', sa.Boolean(), nullable=False),
    sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('acquired_guests_count', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['referred_by'], ['mediator_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediator_profiles_id'), 'mediator_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_mediator_profiles_referral_code'), 'mediator_profiles', ['referral_code'], unique=True)
    op.create_index('ix_mediator_profiles_type_status', 'mediator_profiles', ['mediator_type', 'verification_status'], unique=False)
    op.create_index(op.f('ix_mediator_profiles_user_id'), 'mediator_profiles', ['user_id'], unique=True)
    op.create_table('mediator_reliability_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('guest_satisfaction', sa.Float(), nullable=False),
    sa.Column('response_speed', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('score_tier', sa.String(length=30), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('completed_bookings', sa.Integer(), nullable=False),
    sa.Column('cancelled_bookings', sa.Integer(), nullable=False),
    sa.Column('disputed_bookings', sa.Integer(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('no_show_visits', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediator_reliability_scores_id'), 'mediator_reliability_scores', ['id'], unique=False)
    op.create_index(op.f('ix_mediator_reliability_scores_mediator_id'), 'mediator_reliability_scores', ['mediator_id'], unique=True)
    op.create_table('mediator_wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediator_wallet_transactions_id'), 'mediator_wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_mediator_wallet_transactions_mediator_id'), 'mediator_wallet_transactions', ['mediator_id'], unique=False)
    op.add_column('bookings', sa.Column('mediator_id', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('payment_mode', sa.String(length=30), nullable=False, server_default='online'))
    op.add_column('bookings', sa.Column('visit_request_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bookings_mediator_id'), 'bookings', ['mediator_id'], unique=False)
    op.create_foreign_key(None, 'bookings', 'users', ['mediator_id'], ['id'])
    op.add_column('ping_sessions', sa.Column('mediator_id', sa.Integer(), nullable=True))
    op.add_column('ping_sessions', sa.Column('ping_type', sa.String(length=20), nullable=False, server_default='single'))
    op.add_column('ping_sessions', sa.Column('bulk_ping_group_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_ping_sessions_bulk_ping_group_id'), 'ping_sessions', ['bulk_ping_group_id'], unique=False)
    op.create_index(op.f('ix_ping_sessions_mediator_id'), 'ping_sessions', ['mediator_id'], unique=False)
    op.create_foreign_key(None, 'ping_sessions', 'users', ['mediator_id'], ['id'])
    op.add_column('users', sa.Column('acquired_by_mediator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['acquired_by_mediator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'acquired_by_mediator_id')
    op.drop_constraint(None, 'ping_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_ping_sessions_mediator_id'), table_name='ping_sessions')
    op.drop_index(op.f('ix_ping_sessions_bulk_ping_group_id'), table_name='ping_sessions')
    op.drop_column('ping_sessions', 'bulk_ping_group_id')
    op.drop_column('ping_sessions', 'ping_type')
    op.drop_column('ping_sessions', 'mediator_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_mediator_id'), table_name='bookings')
    op.drop_column('bookings', 'visit_request_id')
    op.drop_column('bookings', 'payment_mode')
    op.drop_column('bookings', 'mediator_id')
    op.drop_index(op.f('ix_mediator_wallet_transactions_mediator_id'), table_name='mediator_wallet_transactions')
    op.drop_index(op.f('ix_mediator_wallet_transactions_id'), table_name='mediator_wallet_transactions')
    op.drop_table('mediator_wallet_transactions')
    op.drop_index(op.f('ix_mediator_reliability_scores_mediator_id'), table_name='mediator_reliability_scores')
    op.drop_index(op.f('ix_mediator_reliability_scores_id'), table_name='mediator_reliability_scores')
    op.drop_table('mediator_reliability_scores')
    op.drop_index(op.f('ix_mediator_profiles_user_id'), table_name='mediator_profiles')
    op.drop_index('ix_mediator_profiles_type_status', table_name='mediator_profiles')
    op.drop_index(op.f('ix_mediator_profiles_referral_code'), table_name='mediator_profiles')
    op.drop_index(op.f('ix_mediator_profiles_id'), table_name='mediator_profiles')
    op.drop_table('mediator_profiles')
    op.drop_index(op.f('ix_mediator_penalties_mediator_id'), table_name='mediator_penalties')
    op.drop_index(op.f('ix_mediator_penalties_id'), table_name='mediator_penalties')
    op.drop_table('mediator_penalties')
    # ### end Alembic commands ###
