"""v2_guest_access_trip_card_commissions

Revision ID: 393cb0a18d49
Revises: f54c8eaf2286
Create Date: 2026-03-18 14:28:38.495969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393cb0a18d49'
down_revision: Union[str, None] = 'f54c8eaf2286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_access_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_mediator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_to_password', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_mediator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_token_hash')
    )
    op.create_index(op.f('ix_guest_access_codes_id'), 'guest_access_codes', ['id'], unique=False)
    op.create_index(op.f('ix_guest_access_codes_phone'), 'guest_access_codes', ['phone'], unique=False)
    op.create_index(op.f('ix_guest_access_codes_user_id'), 'guest_access_codes', ['user_id'], unique=False)
    op.create_table('guest_acquisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('first_booking_id', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('residual_commission_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_residual_earned', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['first_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_acquisitions_guest_id'), 'guest_acquisitions', ['guest_id'], unique=True)
    op.create_index(op.f('ix_guest_acquisitions_id'), 'guest_acquisitions', ['id'], unique=False)
    op.create_index(op.f('ix_guest_acquisitions_mediator_id'), 'guest_acquisitions', ['mediator_id'], unique=False)
    op.create_table('mediator_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('booking_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payout_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mediator_commissions_booking_id'), 'mediator_commissions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_mediator_commissions_id'), 'mediator_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_mediator_commissions_mediator_id'), 'mediator_commissions', ['mediator_id'], unique=False)
    op.create_index('ix_mediator_commissions_type_status', 'mediator_commissions', ['commission_type', 'status'], unique=False)
    op.create_table('trip_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_ref', sa.String(length=20), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('guest_latitude', sa.Float(), nullable=True),
    sa.Column('guest_longitude', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_arrival_minutes', sa.Integer(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_instructions', sa.Text(), nullable=True),
    sa.Column('access_code', sa.String(length=20), nullable=True),
    sa.Column('owner_notified_en_route', sa.Boolean(), nullable=False),
    sa.Column('owner_notified_arrival', sa.Boolean(), nullable=False),
    sa.Column('guest_rating_stay', sa.Integer(), nullable=True),
    sa.Column('guest_rating_mediator', sa.Integer(), nullable=True),
    sa.Column('rating_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_trip_cards_card_ref'), 'trip_cards', ['card_ref'], unique=True)
    op.create_index(op.f('ix_trip_cards_guest_id'), 'trip_cards', ['guest_id'], unique=False)
    op.create_index(op.f('ix_trip_cards_id'), 'trip_cards', ['id'], unique=False)
    op.create_table('visit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_ref', sa.String(length=20), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('guest_phone', sa.String(length=15), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('tour_session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('guest_choice_property_id', sa.Integer(), nullable=True),
    sa.Column('guest_choice_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_open_count', sa.Integer(), nullable=False),
    sa.Column('guest_browsed_properties', sa.Boolean(), nullable=False),
    sa.Column('guest_search_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_choice_property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_session_id'], ['tour_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_cards_card_ref'), 'visit_cards', ['card_ref'], unique=True)
    op.create_index(op.f('ix_visit_cards_id'), 'visit_cards', ['id'], unique=False)
    op.create_index(op.f('ix_visit_cards_mediator_id'), 'visit_cards', ['mediator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_cards_mediator_id'), table_name='visit_cards')
    op.drop_index(op.f('ix_visit_cards_id'), table_name='visit_cards')
    op.drop_index(op.f('ix_visit_cards_card_ref'), table_name='visit_cards')
    op.drop_table('visit_cards')
    op.drop_index(op.f('ix_trip_cards_id'), table_name='trip_cards')
    op.drop_index(op.f('ix_trip_cards_guest_id'), table_name='trip_cards')
    op.drop_index(op.f('ix_trip_cards_card_ref'), table_name='trip_cards')
    op.drop_table('trip_cards')
    op.drop_index('ix_mediator_commissions_type_status', table_name='mediator_commissions')
    op.drop_index(op.f('ix_mediator_commissions_mediator_id'), table_name='mediator_commissions')
    op.drop_index(op.f('ix_mediator_commissions_id'), table_name='mediator_commissions')
    op.drop_index(op.f('ix_mediator_commissions_booking_id'), table_name='mediator_commissions')
    op.drop_table('mediator_commissions')
    op.drop_index(op.f('ix_guest_acquisitions_mediator_id'), table_name='guest_acquisitions')
    op.drop_index(op.f('ix_guest_acquisitions_id'), table_name='guest_acquisitions')
    op.drop_index(op.f('ix_guest_acquisitions_guest_id'), table_name='guest_acquisitions')
    op.drop_table('guest_acquisitions')
    op.drop_index(op.f('ix_guest_access_codes_user_id'), table_name='guest_access_codes')
    op.drop_index(op.f('ix_guest_access_codes_phone'), table_name='guest_access_codes')
    op.drop_index(op.f('ix_guest_access_codes_id'), table_name='guest_access_codes')
    op.drop_table('guest_access_codes')
    # ### end Alembic commands ###
