"""v2_visit_requests_and_tours

Revision ID: f54c8eaf2286
Revises: 35a5913fdbe6
Create Date: 2026-03-18 14:23:36.410959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54c8eaf2286'
down_revision: Union[str, None] = '35a5913fdbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_ref', sa.String(length=20), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_stops', sa.Integer(), nullable=False),
    sa.Column('current_stop_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extended', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booked_property_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booked_property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_sessions_id'), 'tour_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_tour_sessions_mediator_id'), 'tour_sessions', ['mediator_id'], unique=False)
    op.create_index(op.f('ix_tour_sessions_tour_ref'), 'tour_sessions', ['tour_ref'], unique=True)
    op.create_table('visit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_ref', sa.String(length=20), nullable=False),
    sa.Column('mediator_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('guest_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ping_session_id', sa.Integer(), nullable=True),
    sa.Column('tour_session_id', sa.Integer(), nullable=True),
    sa.Column('tour_stop_order', sa.Integer(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hold_extended', sa.Boolean(), nullable=False),
    sa.Column('pass_reason', sa.Text(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mediator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ping_session_id'], ['ping_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tour_session_id'], ['tour_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_requests_id'), 'visit_requests', ['id'], unique=False)
    op.create_index(op.f('ix_visit_requests_mediator_id'), 'visit_requests', ['mediator_id'], unique=False)
    op.create_index('ix_visit_requests_mediator_status', 'visit_requests', ['mediator_id', 'status'], unique=False)
    op.create_index(op.f('ix_visit_requests_property_id'), 'visit_requests', ['property_id'], unique=False)
    op.create_index('ix_visit_requests_property_status', 'visit_requests', ['property_id', 'status'], unique=False)
    op.create_index(op.f('ix_visit_requests_visit_ref'), 'visit_requests', ['visit_ref'], unique=True)
    op.create_table('tour_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('stop_index', sa.Integer(), nullable=False),
    sa.Column('visit_request_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tour_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_request_id'], ['visit_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_stops_id'), 'tour_stops', ['id'], unique=False)
    op.create_index(op.f('ix_tour_stops_tour_id'), 'tour_stops', ['tour_id'], unique=False)
    op.create_index('ix_tour_stops_tour_status', 'tour_stops', ['tour_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tour_stops_tour_status', table_name='tour_stops')
    op.drop_index(op.f('ix_tour_stops_tour_id'), table_name='tour_stops')
    op.drop_index(op.f('ix_tour_stops_id'), table_name='tour_stops')
    op.drop_table('tour_stops')
    op.drop_index(op.f('ix_visit_requests_visit_ref'), table_name='visit_requests')
    op.drop_index('ix_visit_requests_property_status', table_name='visit_requests')
    op.drop_index(op.f('ix_visit_requests_property_id'), table_name='visit_requests')
    op.drop_index('ix_visit_requests_mediator_status', table_name='visit_requests')
    op.drop_index(op.f('ix_visit_requests_mediator_id'), table_name='visit_requests')
    op.drop_index(op.f('ix_visit_requests_id'), table_name='visit_requests')
    op.drop_table('visit_requests')
    op.drop_index(op.f('ix_tour_sessions_tour_ref'), table_name='tour_sessions')
    op.drop_index(op.f('ix_tour_sessions_mediator_id'), table_name='tour_sessions')
    op.drop_index(op.f('ix_tour_sessions_id'), table_name='tour_sessions')
    op.drop_table('tour_sessions')
    # ### end Alembic commands ###
